[package]
name = "cake-gui"
version = "0.1.0"
edition = "2018"
workspace = "../.."

[dependencies]
winit = "0.24"
wgpu = "0.8.1"
imgui = "0.7"
imgui-wgpu = "0.15.1"
stretch = "0.3.2"

futures = "0.3"
imgui-winit-support = "0.7"
image = "0.23.14"
